### ISSUE TITLE
npm run build之后有问题

### ISSUE THREAD

**Issue by tangqiMaster** [jiwenjiang/angularSeed#2]
在npm run build之后再执行npm run start会报错，无法运行了。

**Comment by jiwenjiang** [comment]
我拉下来，本地测了一下，没有问题，不知道是否跟node环境有关，我本地node版本为v7.8.0，因为下面那个node脚本需要v7以上运行

**Comment by tangqiMaster** [comment]
不好意思，是我本地node进程没杀掉之前7070端口，重复Npm run start就出错了，嘻嘻

**Comment by jiwenjiang** [comment]
ok，解决问题就好
