### ISSUE TITLE
路由配置完页面没内容

### ISSUE THREAD

**Issue by Wulawa** [jiwenjiang/angularSeed#3]
用命令set了一个component  在路由中添加后页面没有内容
`
.state('system', {
  url:'/system',
  template: '<system></system>'
 }
`

**Comment by Wulawa** [comment]
知道原因了set 命令生成的index中 'template'  被set文件46行.replace(/temp/g, name)替换成了name ate

**Comment by jiwenjiang** [comment]
您好，需要我这边帮忙吗，没太看懂什么意思。。
