### ISSUE TITLE
请问app.js中的this.class=style和home/index.js中的this.style=style是什么用法？

### ISSUE THREAD

**Issue by xuanyuan** [jiwenjiang/angularSeed#5]
如题

**Comment by jiwenjiang** [comment]
es6 / this.xxx指向当前类
[http://es6.ruanyifeng.com/#docs/class](url)

**Comment by xuanyuan** [comment]
这种添加样式的方式需要配合webpack使用吗？还有就是如何同html页面进行绑定？可以详细说明一下吗？
